op <- par(no.readonly = TRUE)
data.file <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
indate <- ( data.file[,1] == "1/2/2007" ) | (data.file[,1] == "2/2/2007")
data.sub <- subset(data.file, indate)
data.dated <- data.sub
data.dated[,1] <- as.Date(data.dated[,1], "%d/%m/%Y")
# head(subset(data.file, data.file[,1] == "1/2/2007"))
datetime <- paste(as.Date(data.dated[,1], "%d/%m/%Y"), data.dated[,2])
date.strip <- strptime(datetime, "%Y-%m-%d %H:%M:%S")
# data.dated[,10] <- date.strip
# hist(data.dated$Global_active_power)
data.file <- c()
date.posct <- as.POSIXct(datetime)
data.dated[,10] <- date.posct
with(data.dated, plot(data.dated[,10], data.dated$Sub_metering_1, xlab ="", ylab = "Energy sub metering", type = "n"))
with(data.dated, lines(data.dated[,10], data.dated$Sub_metering_1, col ="black"))
with(data.dated, lines(data.dated[,10], data.dated$Sub_metering_2, col ="red"))
with(data.dated, lines(data.dated[,10], data.dated$Sub_metering_3, col ="blue"))
legend("topright", pch = "-", col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, file = "plot3.png")
dev.off()